### ISSUE TITLE
SRTM data for benchmark_data is not available

### ISSUE THREAD

**Issue by neperin** [perrygeo/python-rasterstats#257] opened 2022-04-21 19:44 UTC
There is a link in the example/benchmark.py for downloading SRTM data as part of benchmark_data. It seems the data is not available now.
the link is:
https://hc.app.box.com/shared/1yidaheouv

**Comment by perrygeo** [comment] 2022-05-24 16:54
duplicate of #157, and that link does not appear to be valid.

**Closed by perrygeo** 2022-05-24 16:54 UTC
