### ISSUE TITLE
Wrong mean/std stats

### ISSUE THREAD

**Issue by fri-end** [perrygeo/python-rasterstats#129] opened 2016-09-08 04:56 UTC
Hi,

I think there is an error in calculating mean and standard deviation in rasterstats 0.10.3
Here is the statistics calculated in ArcMap for my region:  
**Band  COUNT   MIN MAX MEAN    STD MEDIAN**
1   151057  1378    2399    1584    71  1577
2   151057  1025    2753    1318    119 1305
3   151057  594 3271    1035    191 1014
4   151057  380 3636    854 223 826
5   151057  113 4225    753 252 718
6   151057  366 4869    1853    642 1808
7   151057  153 7181    2947    1099    2873
8   151057  121 5926    2577    916 2519
9   151057  13880   59141   51615   3675    52475
10  151057  14939   44531   37989   1722    38133
11  151057  10063   56708   48523   3707    49289
12  151057  13024   46146   34272   5463    34959
13  151057  23169   59005   46253   3292    46804

And here is the same statistics calculated using rasterstats (have a look at _mean_ and _std_ values for bands 9-13):  
**Band  count   min max mean    std percentile_50**
1   151057  1378    2399    1584    71  1577
2   151057  1025    2753    1318    119 1305
3   151057  594 3271    1035    191 1014
4   151057  380 3636    854 223 826
5   151057  113 4225    753 252 718
6   151057  366 4869    1853    642 1808
7   151057  153 7181    2947    1099    2873
8   151057  121 5926    2577    916 2519
9   151057  13880   59141   23182   28669   52475
10  151057  14939   44531   9556    28485   38133
11  151057  10063   56708   20090   28673   49289
12  151057  13024   46146   5839    28953   34959
13  151057  23169   59005   17820   28623   46804

The code to reproduce the results using rasterstats:
`for i in range(1, 14):`
`stats = zonal_stats('F:/test.shp', "F:/test_2.dat", stats=['count','min', 'max', 'mean', 'std', 'percentile_50'], all_touched=False, band_num=i, nodata=0)`

Here is the data: https://www.dropbox.com/sh/e8g0jwr1ci0vp2r/AAATlwU2eFjtbtMCO3R5SB1Fa?dl=0

Can you please let me know what the problem could be?

**Comment by fri-end** [comment] 2016-09-08 05:34
UPDATE: when I convert the image from 16 bit unsigned to 32 bit float, _mean_ and _std_ are calculated correctly

**Comment by perrygeo** [comment] 2016-09-08 11:58
I'm not able to reproduce. Even with the `uint16` image (`test_2.dat`), I get results identical to the ArcMap results:

**Band	COUNT	MIN	MAX	MEAN	STD	MEDIAN**
1 151057 1378 2399 1584 71 1577
2 151057 1025 2753 1318 119 1305
3 151057 594 3271 1035 191 1014
4 151057 380 3636 854 223 826
5 151057 113 4225 753 252 718
6 151057 366 4869 1853 642 1808
7 151057 153 7181 2947 1099 2873
8 151057 121 5926 2577 916 2519
9 151057 13880 59141 51615 3675 52475
10 151057 14939 44531 37989 1722 38133
11 151057 10063 56708 48523 3707 49289
12 151057 13024 46146 34272 5463 34959
13 151057 23169 59005 46253 3292 46804

I can't see how the second table would be produced, unless it was using a different raster than the one you provided in the dropbox link.

**Comment by fri-end** [comment] 2016-09-09 00:57
Thank for looking into this @perrygeo 
Unfortunately my issue remains, and it's definitely not related to the use of a different raster. To make our comparisons easier I extracted just one band (`uint16`) (see: http://goo.gl/XYbIcJ) where after running: 
`stats = zonal_stats('test.shp', 'band1.dat', stats="mean", nodata=0)`
 I'm getting 9556 instead of 37989. And as I said before, after converting `uint16` to `float32`, I'm getting the correct result.
I guess, it has something to do with my setup. I'm testing on Windows x64, and I installed rasterstats using _rasterstats-0.10.3-py2-none-any.whl_. I guess I am forced to convert all my imagery into _float32_ format now.

**Comment by sgoodm** [comment] 2016-09-20 20:30
what version of rasterio are you using? try updating that if needed

**Comment by fri-end** [comment] 2016-09-20 23:13
It's up-to-date (i.e. rasterio==0.36.0) and was installed using _rasterio-0.36.0-cp27-cp27m-win_amd64.whl_

**Comment by perrygeo** [comment] 2017-03-05 18:09
This looks like a an issue specific to your platform/installation. I can't reproduce it on any installations and its not clear that there is anything I can do from the code side.  My best guess is some sort of binary incompatibility between some of the C components - improperly installed versions of numpy, GDAL, rasterio, shapely,  fiona and python itself (maybe its 32-bit?) might be at fault here.

If you can find a way to reproduce this error in another environment, please reopen.

**Comment by jeueblah** [comment] 2018-02-19 21:14
I am having a very similar issue. My raster data are uint16. QGIS computes what I believe are correct stats, while rasterstats gives garbage values (for sum). Unfortunately, my raster is global extent, 30m so converting it to float isn't feasible (and I have multiple global rasters in uintXX). Also on a Win10 x64 system. Rasterstats version 0.12.0, rasterio version 0.36.0.

**Comment by jeueblah** [comment] 2018-02-19 21:45
I should note that I was able to debug this (not sure if it needs to be "fixed" in more places, though).

When you create the masked array, numpy by default makes it the same datatype as the input data. When I added ", dtype=np.float" to line 170 [here](https://github.com/perrygeo/python-rasterstats/blob/master/src/rasterstats/main.py), I got the same values as QGIS (and much much faster, thanks for writing this software!). I'm not sure why this behavior exists; must have something to do with the way numpy stores intermediate results when calling sum()?

**Comment by perrygeo** [comment] 2018-02-20 07:38
@jeueblah thanks for the report. Given that we have multiple reports of the problem on win10 x64, I'm going to reopen and investigate further.

I don't currently have access to a Win 10 machine but I'll do my best.

**Comment by perrygeo** [comment] 2018-02-20 09:38
I think we might have a `numpy` distribution issue.

❓ Can anyone reproduce the problem using:
* windows 64bit
* Official Python.org distribution
* numpy 1.14 wheels from pypi

**Comment by perrygeo** [comment] 2018-02-21 03:37
I found a windows machine to test on :-) but I don't have a copy of the data to reproduce it and the dropbox links are 404ing :-(

@fri-end can you send me an updated link to the dataset?

**Comment by fri-end** [comment] 2018-02-21 05:50
@perrygeo unfortunately that dataset is long gone

**Comment by jeueblah** [comment] 2018-02-21 17:18
I gotchu fam. Here are my data that expose the bug. https://drive.google.com/open?id=1mgWIVUM0HkOFNMmcm_fBhDaNy1tkfFa7

**Without dtype=np.float:**
[{'count': 22625585, 'sum': 1396284338.0},
 {'count': 212501, 'sum': 25293972.0},
 {'count': 305003, 'sum': 25457696.0},
 {'count': 221494, 'sum': 20968219.0},
 {'count': 1649505, 'sum': 362830813.0},
 {'count': 205705, 'sum': 13864265.0},
 {'count': 439389, 'sum': 40465001.0},
 {'count': 555130, 'sum': 43869294.0},
 {'count': 554943, 'sum': 58234289.0},
 {'count': 192363, 'sum': 11353189.0},
 {'count': 236805, 'sum': 15387852.0},
 {'count': 121387, 'sum': 6349592.0},
 {'count': 1472733, 'sum': 160577428.0},
 {'count': 306673, 'sum': 13142182.0},
 {'count': 220197, 'sum': 9357941.0},
 {'count': 356920, 'sum': 13157448.0},
 {'count': 140968, 'sum': 4057913.0},
 {'count': 138541, 'sum': 3196803.0},
 {'count': 153863, 'sum': 2930441.0}]

**With dtype=np.float**
[{'count': 22625585, 'sum': 31461055410.0},
 {'count': 212501, 'sum': 25293972.0},
 {'count': 305003, 'sum': 25457696.0},
 {'count': 221494, 'sum': 20968219.0},
 {'count': 1649505, 'sum': 362830813.0},
 {'count': 205705, 'sum': 13864265.0},
 {'count': 439389, 'sum': 40465001.0},
 {'count': 555130, 'sum': 43869294.0},
 {'count': 554943, 'sum': 58234289.0},
 {'count': 192363, 'sum': 11353189.0},
 {'count': 236805, 'sum': 15387852.0},
 {'count': 121387, 'sum': 6349592.0},
 {'count': 1472733, 'sum': 160577428.0},
 {'count': 306673, 'sum': 13142182.0},
 {'count': 220197, 'sum': 9357941.0},
 {'count': 356920, 'sum': 13157448.0},
 {'count': 140968, 'sum': 4057913.0},
 {'count': 138541, 'sum': 3196803.0},
 {'count': 153863, 'sum': 2930441.0}]

**Comment by jeueblah** [comment] 2018-02-22 00:54
I should note that upon comparing the with/without np.dtype=float, it appears that there is an upper limit (all the sums are the same except the first one, which is the biggest feature in the shapefile). I am adding another shapefile to the Drive--same name but without "inc". The features in it are larger, so the bug will be more evident (i.e. not just in the first feature).

**Comment by perrygeo** [comment] 2018-02-22 05:10
I'm now 100% sure that we're seeing this numpy bug: https://github.com/numpy/numpy/issues/8433

The short version: numpy casts to 32 bit integers even on 64-bit windows. The means that any zonal stats sum greater than 2147483647 will overflow and cause incorrect values on that platform.

Ideally this would be fixed in numpy. But until then, I would like to include a workaround. Casting to `float` for all cases is not going to work as it would cause a breaking change for some applications.

Currently my best idea is to cast the masked array to `int64` explicitly _if_ the input is an int dtype and the platform is win 64 bit. I need to do some testing to ensure this is safe.

**Closed** 2018-02-22 05:55 UTC

**Comment by perrygeo** [comment] 2018-02-22 05:59
Fixed in version [`0.12.1`](https://pypi.python.org/pypi/rasterstats/0.12.1).

@fri-end @jeueblah `pip install --upgrade rasterstats` should fix this issue. Thanks for the help - I learned a lot!
