### ISSUE TITLE
Problems caused by special affine transformation

### ISSUE THREAD

**Issue by jingx15** [perrygeo/python-rasterstats#186] opened 2019-04-22 14:26 UTC
When I deal with some special data with special affine matrix, I found it will go bad. The data looks like this. And its affine matrix is like (-1, 0, 180,0, -1, 90) . 

![image](https://user-images.githubusercontent.com/18234905/56505055-17eff600-654d-11e9-9a10-c22ac6dad607.png)
So that `out = np.ones(shape=window_shape) * nodata` in `io.py` file's  185 row will raise a error for `window_shape`<0.

**Comment by perrygeo** [comment] 2019-04-23 13:23
This is a duplicate of #98 - in short, we make assumptions about the affine transform being the standard "north-up" orientation and recommend pre-processing your data accordingly. Please add any  additional details in #98

**Closed by perrygeo** 2019-04-23 13:23 UTC
